#!/system/bin/sh

LOG_FILE=/data/Tweak.log
LOG_FILE_SQL=/data/Tweak_sqlite.log
LogcatOF= "false";
ZipalignOF= "true";
ZIPALIGNDB=/data/Tweak_zipalign.db;
RUN_EVERY=604800;
CURRDATE=`date +%s`

echo "" | tee -a $LOG_FILE
echo "--> Start" | tee -a $LOG_FILE
echo "" | tee -a $LOG_FILE



#zipalign对齐
if [ $ZipalignOF = "true" ]; then

if [ ! -f $ZIPALIGNDB ]; then
    APKDIR=/system/app;
	touch $ZIPALIGNDB;
fi;

echo "--> 全自动Zipalign开始" | tee -a $LOG_FILE

for DIR in $APKDIR ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
      echo "-此APK已经对齐过: $DIR/$APK" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "-此APK已经对齐过: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "-开始处理: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done
busybox mount -o ro,remount /system
touch $ZIPALIGNDB
echo "--> 全自动Zipalign结束"| tee -a $LOG_FILE

else
echo "--> 全自动Zipalign关"| tee -a $LOG_FILE

fi

if [ -e $LOG_FILE_SQL ]; then
    LASTRUN=`stat -t $LOG_FILE_SQL | awk '{print $14}'`
else
    LASTRUN=0
fi;

INTERVAL=$(expr $CURRDATE - $LASTRUN)

if [ $INTERVAL -gt $RUN_EVERY ];
then
    if [ -e $LOG_FILE_SQL ]; then
        rm $LOG_FILE_SQL;
    fi;
        
    echo "数据库整理开始 时间： $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE_SQL;
    echo "--每隔一周进行一次" | tee -a $LOG_FILE_SQL;

    for i in `busybox find /d* -iname "*.db"`; do
        /system/xbin/sqlite3 $i 'REINDEX;';
        resIndex=$?
        if [ $resIndex == 0 ]; then
            resIndex="成功";
        else
            resIndex="错误代码-$resIndex";
        fi;
        echo "数据库 $i  整理：$resIndex" | tee -a $LOG_FILE_SQL;
    done
      
    echo "数据库整理结束 时间： $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE_SQL;
fi;

#清理垃圾、阻止垃圾生成
if [ "$LogcatOF" = "false" ]; then
rm /dev/log/main;
rm -r /data/local/tmp/*
rm -r /data/tmp/*
rm -r /data/system/usagestats/*
rm -r /data/system/appusagestats/*
rm -r /data/system/dropbox/*
rm -r /data/tombstones/*
rm -r /data/anr/*
busybox chmod 000 /data/system/userbehavior.db;
busybox chmod 000 /data/system/usagestats/;
busybox chmod 000 /data/system/dropbox/;
busybox chmod 000 /data/anr/;
busybox chmod 000 /data/tombstones/;
busybox chmod 000 /data/system/appusagestats/;

else
echo "--> 允许Log与LogCat生成"| tee -a $LOG_FILE
busybox chmod 777 /data/system/userbehavior.db;
busybox chmod 777 /data/system/usagestats/;
busybox chmod 777 /data/system/dropbox/;
busybox chmod 777 /data/anr/;
busybox chmod 777 /data/tombstones/;
busybox chmod 777 /data/system/appusagestats/;
fi;

sleep 50

echo "--> End-Time： $( date +"%H:%M:%S" )" | tee -a $LOG_FILE

