#!/system/bin/sh

LOG_FILE=/data/Tweak.log
LOG_FILE_SQL=/data/Tweak_sqlite.log
LogcatOF=false
RUN_EVERY=604800;
CURRDATE=`date +%s`

echo "" | tee -a $LOG_FILE
echo "--> Start" | tee -a $LOG_FILE


if [ -e $LOG_FILE_SQL ]; then
    LASTRUN=`stat -t $LOG_FILE_SQL | awk '{print $14}'`
else
    LASTRUN=0
fi;

INTERVAL=$(expr $CURRDATE - $LASTRUN)

if [ $INTERVAL -gt $RUN_EVERY ];
then
    if [ -e $LOG_FILE_SQL ]; then
        rm $LOG_FILE_SQL;
    fi;
        
    echo "数据库整理开始 时间： $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE_SQL;
    echo "--每隔一周进行一次" | tee -a $LOG_FILE_SQL;

    for i in `busybox find /d* -iname "*.db"`; do
        /system/xbin/sqlite3 $i 'REINDEX;';
        resIndex=$?
        if [ $resIndex == 0 ]; then
            resIndex="成功";
        else
            resIndex="错误代码-$resIndex";
        fi;
        echo "数据库 $i  整理：$resIndex" | tee -a $LOG_FILE_SQL;
    done
      
    echo "数据库整理结束 时间： $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE_SQL;
fi;

#清理垃圾、阻止垃圾生成
echo "--> 禁止Log与LogCat生成"| tee -a $LOG_FILE
if [ "$LogcatOF" = "false" ]; then
rm /dev/log/main;
rm -r /data/local/tmp/*
rm -r /data/tmp/*
rm -r /data/system/usagestats/*
rm -r /data/system/appusagestats/*
rm -r /data/system/dropbox/*
rm -r /data/tombstones/*
rm -r /data/anr/*
busybox chmod 000 /data/system/userbehavior.db;
busybox chmod 000 /data/system/usagestats/;
busybox chmod 000 /data/system/dropbox/;
busybox chmod 000 /data/anr/;
busybox chmod 000 /data/tombstones/;
busybox chmod 000 /data/system/appusagestats/;

else
echo "--> 允许Log与LogCat生成"| tee -a $LOG_FILE
busybox chmod 777 /data/system/userbehavior.db;
busybox chmod 777 /data/system/usagestats/;
busybox chmod 777 /data/system/dropbox/;
busybox chmod 777 /data/anr/;
busybox chmod 777 /data/tombstones/;
busybox chmod 777 /data/system/appusagestats/;
fi;

sleep 50

echo "--> End-Time： $( date +"%H:%M:%S" )" | tee -a $LOG_FILE

